
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[295] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  104,  102,   90,   90,   78,  102,
       93,   84,   77,  102,   72,   73,   82,   81,   69,   80,
       35,   83,   38,   38,   70,   66,   85,   71,   86,   89,
       35,   35,   35,   74,   75,   87,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   67,   88,   68,   79,  103,   96,  103,  103,
       97,  103,   99,  100,  101,   90,   65,    0,   43,    0,
       51,   68,   60,   52,    0,    0,   49,   57,   47,   58,
       48,   59,   35,   35,   35,   91,    0,   50,   41,   37,

        0,   38,    0,   38,   75,   67,   74,   56,   62,   64,
       63,   55,    0,    0,   35,   53,   35,   35,   35,   35,
       35,   35,    9,   35,   35,   35,   35,   35,   35,   17,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   54,   61,   96,    0,    0,    0,    0,   97,
        0,   98,   99,  100,   42,   35,   35,   35,    0,   92,
       41,    0,   41,   37,    0,   39,   36,   46,   45,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   15,   35,   18,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

        0,    0,    0,   35,    0,   41,   39,   36,   35,    1,
       35,    3,    4,   35,   35,   35,   35,   11,   12,   35,
       35,   16,   19,   34,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   31,   35,   35,    0,    0,
       40,   35,    2,    6,   35,   35,   35,   35,   14,   35,
       35,   22,   35,   35,   35,   35,   35,   35,   29,   35,
       35,   33,    0,    0,   40,    5,   35,   35,   10,   13,
       35,   21,   23,   24,   25,   26,   27,   35,   35,   35,
       95,    0,   35,    8,   35,   28,   35,   35,   94,    7,
       20,   30,   32,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   32,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   30,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   30,   48,   49,   50,   51,
       52,   53,   30,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    4,    5,    1,    6,    6,
        1,    1,    4,    1,    4,    1,    7,    7,    7,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    7,    7,
        7,    7,    7,    7,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[304] =
    {   0,
        0,    0,   65,   66,   50,   52,  531,  530,  113,    0,
      528,  527,  526,  525,  527,  534,   71,   74,  502,   73,
      534,   56,   73,  489,  534,  534,  500,   69,  534,   70,
       68,   78,  163,  167,  498,  534,   82,  498,   74,  534,
        0,   94,  465,  534,  534,  496,  462,  464,  153,   49,
      153,  136,  465,  157,  464,  458,  471,  171,  452,  461,
      459,  464,  534,  157,  534,  534,  534,  187,  466,  457,
       91,  201,    0,    0,  534,  229,  534,  203,  534,  504,
      534,  534,  534,  534,  183,  212,  534,  534,  534,  534,
      534,  534,  489,  216,    0,  534,  502,  534,  223,  251,

      242,  224,    0,  258,  534,  534,  534,  480,  534,  534,
      534,  479,  205,  466,  447,  534,  444,  456,  443,  458,
      445,  451,  437,  438,  435,  435,  438,  435,  432,    0,
      431,  435,  436,  169,  432,  201,  199,  436,  429,  193,
      179,  434,  534,  534,  248,  437,  428,  434,  436,  268,
      274,  534,    0,    0,  534,    0,  283,    0,  473,  534,
      285,  303,  534,  278,  273,  301,  300,  534,  534,  428,
      422,  434,  429,  417,  269,  431,  429,  425,  417,  423,
      426,    0,  412,    0,  418,  413,  414,  403,  405,  407,
      414,  400,  398,  398,  410,  400,  404,  408,  410,  399,

      400,  397,  317,  319,  321,  323,  534,  320,  394,    0,
      396,    0,    0,  387,  395,  384,  391,    0,    0,  371,
      366,    0,    0,    0,  357,  333,  330,  342,  332,  335,
      340,  339,  337,  327,  331,    0,  319,  331,  322,  314,
      339,  321,    0,    0,  314,  315,  320,  310,    0,  304,
      305,    0,  313,  304,  305,  288,  280,  275,    0,  261,
      263,    0,  263,  256,  534,    0,  239,  229,    0,    0,
      240,    0,    0,    0,    0,    0,    0,  230,  226,  215,
      534,  206,  194,    0,  136,    0,   47,   41,  534,    0,
        0,    0,    0,  534,  388,  395,  402,  409,  412,  416,

      423,  430,  432
    } ;

static yyconst flex_int16_t yy_def[304] =
    {   0,
      294,    1,  295,  295,  295,  295,  295,  295,  294,    9,
      296,  296,  295,  295,  294,  294,  294,  294,  294,  297,
      294,  294,  294,  298,  294,  294,  294,  294,  294,  294,
      299,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      299,  299,  299,  294,  294,  294,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  300,  301,  294,  294,  294,  297,  294,  297,
      294,  294,  294,  294,  298,  298,  294,  294,  294,  294,
      294,  294,  299,  299,  299,  294,  302,  294,  294,  294,

      294,  294,  303,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  297,  298,  299,  294,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  300,  301,  294,  299,  299,  299,  302,  294,
      294,  294,  294,  294,  294,  294,  303,  294,  294,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,

      294,  294,  294,   94,  294,  294,  294,  294,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  294,  294,
      294,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  294,  294,  294,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      294,  294,  299,  299,  299,  299,  299,  299,  294,  299,
      299,  299,  299,    0,  294,  294,  294,  294,  294,  294,

      294,  294,  294
    } ;

static yyconst flex_int16_t yy_nxt[601] =
    {   0,
       16,   17,   18,   17,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   41,   41,   41,
       42,   43,   41,   41,   44,   16,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   41,   54,   41,   55,   41,
       56,   41,   41,   57,   58,   59,   60,   61,   62,   41,
       41,   41,   63,   64,   65,   66,   68,   68,   71,   71,
       71,   71,   76,   76,   76,   76,   76,   76,   79,   81,
       82,   83,   88,  293,   93,   90,   94,   94,  292,  106,
       96,  122,   89,   91,   92,   97,   84,  111,  112,  113,

      123,   98,  107,  114,  108,  109,   69,   69,   80,  150,
      150,   70,   70,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   73,   73,
       67,   67,   67,   67,   67,   73,   67,   73,   67,   73,
       73,   73,   73,   73,   73,   73,   73,   67,   67,   67,
       67,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   67,   67,   67,   67,   99,
      143,  100,  100,   99,  127,  104,  104,  128,  145,  291,
      101,  119,  155,  102,  101,  102,  103,  102,  120,  102,

      130,  124,  151,  125,  121,  101,  152,  131,   79,  101,
       79,  102,  126,  187,  294,  102,  135,  136,   86,  102,
      144,   85,  103,  102,  188,  198,  137,  199,  146,  138,
       76,   76,   76,  147,   94,   94,  290,  192,   80,  196,
       80,  161,  161,  157,  158,  190,  158,  197,  289,  145,
      162,  163,  193,  163,  102,  165,  102,  165,  157,  158,
      166,  166,  191,  288,  158,  162,  163,   99,  287,  100,
      100,  163,  102,  286,   99,  151,  104,  104,  101,  152,
      102,  164,  285,  164,  284,  101,  150,  150,  102,  146,
      102,  166,  166,  101,  147,  283,  203,  282,  203,  164,

      101,  204,  204,  161,  161,  281,  102,  164,  164,  280,
      164,  279,  162,  163,  102,  163,  205,  278,  205,  166,
      166,  206,  206,  214,  215,  277,  164,  162,  163,  207,
      208,  207,  208,  163,  164,  241,  241,  204,  204,  206,
      206,  206,  206,  276,  207,  275,   95,  274,  208,  207,
      208,  163,  208,  163,  273,  272,  208,  241,  241,  271,
      270,   95,  269,  268,  267,  266,  163,  265,  208,  265,
      264,  163,  263,  262,  261,  260,  208,  259,  258,  257,
      256,  255,  265,  254,  253,  252,  251,  265,   67,   67,
       67,   67,   67,   67,   67,   74,   74,   74,   74,   74,

       74,   74,   78,   78,   78,   78,   78,   78,   78,   85,
       85,  250,   85,   85,   85,   85,   95,   95,   95,  153,
      153,  249,  153,  154,  248,  154,  154,  154,  154,  154,
      159,  159,  159,  159,  159,  159,  159,  167,  167,  247,
      246,  245,  244,  243,  242,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      213,  212,  211,  210,  209,  160,  202,  201,  149,  148,
      200,  195,  194,  189,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,

      170,   86,  169,  168,  160,  156,  294,  149,  148,  142,
      141,  140,  139,  134,  133,  132,  129,  118,  117,  116,
      115,  110,  105,   87,   86,   77,  294,   75,   75,   67,
       67,   72,   72,   15,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294

    } ;

static yyconst flex_int16_t yy_chk[601] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    5,
        6,    6,   17,   17,   17,   18,   18,   18,   20,   22,
       22,   23,   28,  288,   31,   30,   31,   31,  287,   37,
       32,   50,   28,   30,   30,   32,   23,   39,   39,   42,

       50,   32,   37,   42,   37,   37,    3,    4,   20,   71,
       71,    3,    4,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   33,
       64,   33,   33,   34,   52,   34,   34,   52,   68,  285,
       33,   49,   85,   33,   34,   33,   33,   34,   49,   34,

       54,   51,   72,   51,   49,   33,   72,   54,   78,   34,
      113,   33,   51,  134,   86,   34,   58,   58,   85,   33,
       64,   86,   33,   34,  134,  141,   58,  141,   68,   58,
       76,   76,   76,   68,   94,   94,  283,  137,   78,  140,
      113,   99,   99,   94,   94,  136,   94,  140,  282,  145,
       99,   99,  137,   99,  102,  101,  102,  101,   94,   94,
      101,  101,  136,  280,   94,   99,   99,  100,  279,  100,
      100,   99,  102,  278,  104,  151,  104,  104,  100,  151,
      102,  100,  271,  100,  268,  104,  150,  150,  104,  145,
      104,  165,  165,  100,  145,  267,  157,  264,  157,  100,

      104,  157,  157,  161,  161,  263,  104,  100,  164,  261,
      164,  260,  161,  161,  104,  161,  162,  258,  162,  166,
      166,  162,  162,  175,  175,  257,  164,  161,  161,  166,
      167,  166,  167,  161,  164,  203,  203,  204,  204,  205,
      205,  206,  206,  256,  166,  255,  204,  254,  167,  166,
      208,  206,  208,  206,  253,  251,  167,  241,  241,  250,
      248,  204,  247,  246,  245,  242,  206,  241,  208,  241,
      240,  206,  239,  238,  237,  235,  208,  234,  233,  232,
      231,  230,  241,  229,  228,  227,  226,  241,  295,  295,
      295,  295,  295,  295,  295,  296,  296,  296,  296,  296,

      296,  296,  297,  297,  297,  297,  297,  297,  297,  298,
      298,  225,  298,  298,  298,  298,  299,  299,  299,  300,
      300,  221,  300,  301,  220,  301,  301,  301,  301,  301,
      302,  302,  302,  302,  302,  302,  302,  303,  303,  217,
      216,  215,  214,  211,  209,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  183,  181,  180,  179,  178,  177,  176,
      174,  173,  172,  171,  170,  159,  149,  148,  147,  146,
      142,  139,  138,  135,  133,  132,  131,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,

      115,  114,  112,  108,   97,   93,   80,   70,   69,   62,
       61,   60,   59,   57,   56,   55,   53,   48,   47,   46,
       43,   38,   35,   27,   24,   19,   15,   14,   13,   12,
       11,    8,    7,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[104] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "simple.l"
#line 2 "simple.l"
/*
**Lexical specification for HCC 1.0
**This code is based on various open resources, intented for educational
**purposes only. You can access, modify this for your personal use freely,
**but any attempts for comercial exploitation from this code are considered 
**unethical and should be discouraged.
*/
#include "c.h"
#include "parser.h"

//file under current compilation
extern char * file;

//column number and line number of current token
//Note that yylineno denotes the line of current token by default,
//but lineno takes the preprocessing pragmas into account
static int yycolno=1;
//static int lineno;

//current token value and coordinates
Tvalue tval;
Coordinate tcoord;

//helper routines

//check if IDENTIFIER is a type name
static int check_type();

//save the coordinate for current token
static void savecoord(void);
//static void printcoord(void);

//deal with C block comments
static void comment(void);

//adjust yycolno
static void advcol(void);

//parse line numbers in preprocessing pragmas
static int icon(void);

//integer parsing
static int parsehexint(void);
static int parseoctint(void);
static int parsedecint(void);
static int parseint(char *s, int len, int base);
static void setint(int tok, int overflow, unsigned int i[], int *l, int *h);

//floating point number
static int parsenumber(void);

//char literal
extern Type wchartype;
static int parsescapechar(char **p, int wide);
static int parsechar(void);

//string literal
static int parsestring(void);
static void expandstr(char **str, char carr[], int len);

//#define LEXER_DEBUG

#ifdef  LEXER_DEBUG
enum 
{
  DUMMYTOKEN = 256,
  #define TK(a,b) a,
  #include "token.h"
  #undef TK
};

static char * tokenstrs[] =
{
  #define TK(a,b) b,
  #include "token.h"
  #undef TK
};
#endif

 
 
 
 
 
 
#line 796 "<stdout>"

#define INITIAL 0
#define PRAGMA 1
#define PRAGMA1 2
#define PRAGMA2 3
#define PRAGMA3 4
#define PRAGMA4 5
#define PRAGMA5 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 102 "simple.l"


#line 987 "<stdout>"
     
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 295 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 534 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 104 "simple.l"
{savecoord(); advcol(); return (AUTO);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "simple.l"
{savecoord(); advcol(); return (BREAK);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "simple.l"
{savecoord(); advcol(); return (CASE);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "simple.l"
{savecoord(); advcol(); return (CHAR);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "simple.l"
{savecoord(); advcol(); return (CHAR);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 109 "simple.l"
{savecoord(); advcol(); return (CONST);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 110 "simple.l"
{savecoord(); advcol(); return (CONTINUE);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 111 "simple.l"
{savecoord(); advcol(); return (DEFAULT);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 112 "simple.l"
{savecoord(); advcol(); return (DO);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 113 "simple.l"
{savecoord(); advcol(); return (DOUBLE);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 114 "simple.l"
{savecoord(); advcol(); return (ELSE);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "simple.l"
{savecoord(); advcol(); return (ENUM);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 116 "simple.l"
{savecoord(); advcol(); return (EXTERN);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "simple.l"
{savecoord(); advcol(); return (FLOAT);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "simple.l"
{savecoord(); advcol(); return (FOR);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "simple.l"
{savecoord(); advcol(); return (GOTO);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "simple.l"
{savecoord(); advcol(); return (IF);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "simple.l"
{savecoord(); advcol(); return (INT);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 "simple.l"
{savecoord(); advcol(); return (LONG);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "simple.l"
{savecoord(); advcol(); return (REGISTER);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 124 "simple.l"
{savecoord(); advcol(); return (RETURN);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "simple.l"
{savecoord(); advcol(); return (SHORT);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 126 "simple.l"
{savecoord(); advcol(); return (SIGNED);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 127 "simple.l"
{savecoord(); advcol(); return (SIZEOF);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "simple.l"
{savecoord(); advcol(); return (STATIC);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 129 "simple.l"
{savecoord(); advcol(); return (STRUCT);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 130 "simple.l"
{savecoord(); advcol(); return (SWITCH);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 131 "simple.l"
{savecoord(); advcol(); return (TYPEDEF);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "simple.l"
{savecoord(); advcol(); return (UNION);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "simple.l"
{savecoord(); advcol(); return (UNSIGNED);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "simple.l"
{savecoord(); advcol(); return (VOID);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "simple.l"
{savecoord(); advcol(); return (VOLATILE);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "simple.l"
{savecoord(); advcol(); return (WHILE);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "simple.l"
{savecoord(); advcol(); tval.p = string("null"); return IDENTIFIER;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "simple.l"
{savecoord(); advcol(); 
                         tval.p = string(yytext); return IDENTIFIER;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 142 "simple.l"
{savecoord(); advcol(); return parsehexint();}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 143 "simple.l"
{savecoord(); advcol(); return parseoctint();}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 144 "simple.l"
{savecoord(); advcol(); return parsedecint();}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 146 "simple.l"
{savecoord(); advcol(); return parsenumber();}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 147 "simple.l"
{savecoord(); advcol(); return parsenumber();}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 148 "simple.l"
{savecoord(); advcol(); return parsenumber();}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 150 "simple.l"
{savecoord(); advcol(); return parsechar();}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 151 "simple.l"
{savecoord(); advcol(); return parsestring();}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 153 "simple.l"
{savecoord(); advcol(); return (ELLIPSIS);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 154 "simple.l"
{savecoord(); advcol(); return (RIGHT_ASSIGN);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 155 "simple.l"
{savecoord(); advcol(); return (LEFT_ASSIGN);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 156 "simple.l"
{savecoord(); advcol(); return (ADD_ASSIGN);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 157 "simple.l"
{savecoord(); advcol(); return (SUB_ASSIGN);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 158 "simple.l"
{savecoord(); advcol(); return (MUL_ASSIGN);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 159 "simple.l"
{savecoord(); advcol(); return (DIV_ASSIGN);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 160 "simple.l"
{savecoord(); advcol(); return (MOD_ASSIGN);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 161 "simple.l"
{savecoord(); advcol(); return (AND_ASSIGN);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 162 "simple.l"
{savecoord(); advcol(); return (XOR_ASSIGN);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 163 "simple.l"
{savecoord(); advcol(); return (OR_ASSIGN);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 164 "simple.l"
{savecoord(); advcol(); return (RIGHT_SHIFT);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 165 "simple.l"
{savecoord(); advcol(); return (LEFT_SHIFT);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 166 "simple.l"
{savecoord(); advcol(); return (INC_OP);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "simple.l"
{savecoord(); advcol(); return (DEC_OP);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 168 "simple.l"
{savecoord(); advcol(); return (PTR_OP);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 169 "simple.l"
{savecoord(); advcol(); return (AND_OP);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 170 "simple.l"
{savecoord(); advcol(); return (OR_OP);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 171 "simple.l"
{savecoord(); advcol(); return (LE_OP);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 172 "simple.l"
{savecoord(); advcol(); return (GE_OP);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 173 "simple.l"
{savecoord(); advcol(); return (EQ_OP);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 174 "simple.l"
{savecoord(); advcol(); return (NE_OP);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 175 "simple.l"
{savecoord(); advcol(); return ';';}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 176 "simple.l"
{savecoord(); advcol(); return '{';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 177 "simple.l"
{savecoord(); advcol(); return '}';}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 178 "simple.l"
{savecoord(); advcol(); return ',';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 179 "simple.l"
{savecoord(); advcol(); return ':';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 180 "simple.l"
{savecoord(); advcol(); return '=';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 181 "simple.l"
{savecoord(); advcol(); return '(';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 182 "simple.l"
{savecoord(); advcol(); return ')';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 183 "simple.l"
{savecoord(); advcol(); return '[';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 184 "simple.l"
{savecoord(); advcol(); return ']';}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 185 "simple.l"
{savecoord(); advcol(); return '.';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 186 "simple.l"
{savecoord(); advcol(); return '&';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 187 "simple.l"
{savecoord(); advcol(); return '!';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 188 "simple.l"
{savecoord(); advcol(); return '~';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 189 "simple.l"
{savecoord(); advcol(); return '-';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 190 "simple.l"
{savecoord(); advcol(); return '+';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 191 "simple.l"
{savecoord(); advcol(); return '*';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 192 "simple.l"
{savecoord(); advcol(); return '/';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 193 "simple.l"
{savecoord(); advcol(); return '%';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 194 "simple.l"
{savecoord(); advcol(); return '<';}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 195 "simple.l"
{savecoord(); advcol(); return '>';}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 196 "simple.l"
{savecoord(); advcol(); return '^';}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 197 "simple.l"
{savecoord(); advcol(); return '|';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 198 "simple.l"
{savecoord(); advcol(); return '?';}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 200 "simple.l"
{advcol();}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 202 "simple.l"
{comment();}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 204 "simple.l"
{yycolno = 1;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 206 "simple.l"
{yycolno++; BEGIN(PRAGMA);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 207 "simple.l"
{savecoord(); 
                              fatal(&tcoord,"Running preprocessor before compiling the program"); 
                              BEGIN(0);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 210 "simple.l"
{savecoord(); 
                              fatal(&tcoord,"Running preprocessor before compiling the program"); 
                              BEGIN(0);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 213 "simple.l"
{yycolno++; BEGIN(PRAGMA1);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 214 "simple.l"
{yylineno = icon() - 1; yycolno++; BEGIN(PRAGMA2);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 215 "simple.l"
{yycolno++; BEGIN(PRAGMA3);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 216 "simple.l"
{file = string(yytext); BEGIN(PRAGMA4);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 217 "simple.l"
{yycolno++; BEGIN(PRAGMA5);}
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 218 "simple.l"
{yycolno=1; BEGIN(0);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 220 "simple.l"
{savecoord(); fatal(&tcoord,"Unknown character");}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 222 "simple.l"
ECHO;
	YY_BREAK
#line 1605 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PRAGMA):
case YY_STATE_EOF(PRAGMA1):
case YY_STATE_EOF(PRAGMA2):
case YY_STATE_EOF(PRAGMA3):
case YY_STATE_EOF(PRAGMA4):
case YY_STATE_EOF(PRAGMA5):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 295 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 295 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 294);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 222 "simple.l"



static int parsenumber(void)
{
  int tok;
  double v;
  char *p = yytext;

  while( isdigit(*p) ) p++;
  if(*p=='.') p++;
  while( isdigit(*p) ) p++;
  if(*p=='E' || *p=='e') {
    p++;
    if(*p=='+' || *p=='-')
      p++;
  }
  while( isdigit(*p) ) p++;

  errno = 0;
  v = strtod(yytext,NULL);
  if(errno == ERANGE)
    warning(&tcoord,"float constant overflow.");
  tval.d = v;

  tok = DOUBLECONST;
  if(*p == 'F' || *p == 'f'){
    p++;
    tval.f = (float)v;
    tok = FLOATCONST;
  }else if(*p == 'l' || *p == 'L') {
    p++;
    tok = LDOUBLECONST;
  }

  if(*p != 0)
    fatal(&tcoord,"invalid float constant");

  return tok;
}

static void expandstr(char **str, char carr[], int len)
{
  char *p;
  
  if(len<=0) 
    return;
  p = (char*)allocate(len+1);
  memcpy(p,(char*)carr,(size_t)len);
  p[len]=0;
  *str = p;
}

static int parsestring(void)
{
  char *p = yytext;
  int ch=0;
  int wide=0;
  char tchar[512];
  int maxlen = 511;
  int i = 0;
  char *str = NULL;

  if( *p == 'L' ) {
    warning(&tcoord,"attempting to use wide string.");
    p++; wide = 1;
  }

  assert(*p++ == '"');

  while(*p != '"') {
    ch = (*p == '\\')?parsescapechar(&p,wide) : *p++;
//    if(ch > 0xff)
//      fatal(&tcoord,"unsupported character in wide string constant");
    tchar[i++] = ch;
    if(i>=maxlen){
      expandstr(&str,tchar,i);
      i = 0;
    }
  }
  expandstr(&str,tchar,i);
  p++; //skip '"'

  if(i>0)
    tval.p = string(str);
  else
    tval.p = "";

  return STRING;
}

static int parsescapechar(char **s, int wide)
{
  unsigned v;
  unsigned maxlimit;
  char *p = *s;

  p++;
  switch(*p++) {
    case 'a': *s = p; return '\a';
    case 'b': *s = p; return '\b';
    case 'f': *s = p; return '\f';
    case 'n': *s = p; return '\n';
    case 'r': *s = p; return '\r';
    case 't': *s = p; return '\t';
    case 'v': *s = p; return '\v';

    case '\'':
    case '\"':
    case '\\':
    case '\?': *s = p; return *(p-1);

    case 'x':
      if(!ishexdigit(*p))
        fatal(&tcoord,"illegal escape sequence constant.");
      v = 0;
      while(ishexdigit(*p)) {
        if(isdigit(*p))
          v = (v<<4) + *p - '0';
        else v = (v<<4) + toupper(*p) - 'A' + 10;
        p++;
      }
      if(wide) {
        switch(wchartype.size) {
          case 1: maxlimit = 0xff; break;
          case 2: maxlimit = 0xffff; break;
          case 4: maxlimit = 0xffffffff; break;
          default: fatal(&tcoord,"wide char size is too large");
        }
      }else maxlimit = 0xff;

      if(v > maxlimit)
        fatal(&tcoord,"hexadecimal escape sequence too large.");
      *s = p;
      return v;

    case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7':
      v = *(p-1) - '0';
      if( isoctdigit(*p)) {
        v = (v<<3) + *p++ - '0';
        if( isoctdigit(*p)) 
          v = (v<<3) + *p++ - '0';
      }
      *s = p;
      return v;

    default: fatal(&tcoord,"unknown escape sequence.");
  }
  return 0;
}

static int parsechar(void)
{
  char *p = yytext;
  int ch=0;
  int wide=0;

  if( *p == 'L' ) {
    warning(&tcoord,"attempting to use wide char.");
    p++; wide = 1;
  }

  assert(*p++ == '\'');
  ch = (*p == '\\')?parsescapechar(&p,wide) : *p++;
  if(*p != '\'')
    fatal(&tcoord,"illegal char constant.");

  tval.i[0] = ch;
  tval.i[1] = 0;
  return INTCONST;
}

static void setint(int tok, int overflow, unsigned int i[], int *l, int *h)
{
  switch(tok) {
    case INTCONST: case LINT:
      if(overflow || i[1] || (i[0] & 0x80000000)) {
        *l = INT_MAX; *h = 0;
        warning(&tcoord,"Integer overflow");
      }else {
        *l = i[0]; *h = 0;
      }
      break;
    case UINT: case ULINT:
      if(overflow || i[1]) {
        *l = UINT_MAX; *h = 0;
        warning(&tcoord,"Unsigned integer overflow");
      }else {
        *l = i[0]; *h = 0;
      }
      break;
    case LLINT:
      if(overflow || (i[1] & 0x80000000)) {
        *l = 0xffffffff;
        *h = 0x7fffffff;
        warning(&tcoord,"Long long integer overflow");
      }else {
        *l = i[0];
        *h = i[1];
      } 
      break;
    case ULLINT:
      if(overflow) {
        *l = 0xffffffff;
        *h = 0xffffffff;
        warning(&tcoord,"unsigned long long integer overflow");
      }else {
        *l = i[0];
        *h = i[1];
      }
      break;
    default: assert(0);
  }
}

static int parseint(char *s, int len, int base)
{
  int tok;
  int overflow = 0;
  int d = 0;
  unsigned int i[2];
  unsigned long long v = 0ull;
  char * p = s;
  char * q = s + len;

  while (p < q) {
    if( (*p >= 'A' && *p <= 'F') || (*p >= 'a' && *p <= 'f') )
      d = toupper(*p) - 'A' + 10;
    else
      d = *p - '0';

    if(v >= ULLINT_MAX - (unsigned long long)d / (unsigned long long)base)
      overflow = 1;
    v = v*(unsigned long long)base+(unsigned long long)d;
    p++;
  }


  i[0] = (unsigned int)(v & (unsigned long long)0xffffffff);
  i[1] = (unsigned int)( (v >> 32) & (unsigned long long)0xffffffff);
  tok = INTCONST;

  if( *p == 'u' || *p == 'U' ) {
    p++;
    tok = UINT;
  }  

  if( *p == 'l' || *p == 'L' ) {
    p++;
    if(tok == INTCONST)
      tok = LINT;
    else if(tok == UINT)
      tok = ULINT;

    if( *p == 'l' || *p == 'L' ) {
      p++;
      if(tok == LINT)
        tok = LLINT;
      else if(tok == ULINT)
        tok = ULLINT;
    }
  }

  if(*p != 0)
    fatal(&tcoord,"Invalid integer constant specification: %s",yytext);

  //printf("tok: %s overflow: %d val: %d %d\n",tokenstrs[tok-DUMMYTOKEN-1],overflow,i[0],i[1]);
  setint(tok,overflow,i,&tval.i[0],&tval.i[1]);
  return tok;
}

static int parsedecint(void)
{
  char *p;

  p = yytext;
  while( isdigit(*p) ) p++;

  return parseint(yytext,p-yytext,10);
}

static int parseoctint(void)
{
  char *p, *s;

  s = p = yytext+1;
  while( isoctdigit(*p) ) p++;

  return parseint(s,p-s,8);
}

static int parsehexint(void)
{
  char *p, *s;

  s = p = yytext+2;

  while( ishexdigit(*p) ) p++;

  return parseint(s,p-s,16);
}

static void comment(void)
{
  char c, c1;

loop:
  while( (c=input()) != '*' && c!=0) {
    if( c== '\n') {
      yycolno = 1; 
    } else 
      yycolno ++;
    //putchar(c);
  }

  if( (c1=input()) != '/' && c!=0 ){
    unput(c1);
    goto loop;
  }

  if(c != 0) {
    //putchar(c1);
    yycolno += 2; 
  }
}

static void advcol(void)
{
  int i;
  for(i=0; yytext[i] != 0; i++)
    if( yytext[i] == '\n'){
      yycolno = 1;
    } else// if (yytext[i] == '\t')
      yycolno ++; //treat TAB as space
}

/*
**Parse the line number in preprocessing directives.
**Examples:
** # line 6 "C:\\path\\to\\header\\file.h" or
** # 6 "/path/to/header/file.h"
**Other directives are ignored 
*/

static int icon(void)
{
  int line;
  int i;

  line = 0;
  for(i=0; yytext[i] != 0; i++,yycolno++){
    assert(isdigit(yytext[i]));
    line = 10 * line + yytext[i] - '0';
  }
  return line;
}

static void savecoord(void)
{
  char* first;
  char* original_file = (char*)malloc((strlen(file)+1)*sizeof(char));
  strcpy(original_file, file);
  first = strtok(original_file, ".");
  sprintf(original_file, "%s.t", first);
  
  tcoord.file = original_file; //file;
  tcoord.line = yylineno;
  if(yylineno>0) {
                 //Modified for Java
    tcoord.line = linenumbers[yylineno-2].original+1;
    //printf("Line is %d, %d\n", yylineno, linenumbers[yylineno-2].original);
  }
  tcoord.column = yycolno;
}

/*
static void printcoord(void)
{
  fprintf(stderr,"file: %s line: %d\n",tcoord.file,tcoord.line);
}
*/

static int check_type()
{
  if(check_typedef(yytext))
    return TYPENAME;

  return IDENTIFIER;
}

#ifdef LEXER_DEBUG
//Sample lexical inputs for test purposes

#if 0
/*
**Comments test
*/

//keywords
auto break case char const continue default do double
else enum extern float for /* more 
comments test*/goto if int long register return
short signed sizeof static struct
switch typedef union unsigned void
volatile
while

//identifiers
abcded, fjdkls;afds

//normal integer constants
0x1234ab
0X32cdef
0x123u
0x13adcbul
0x13adcbull
012345670
012345670ULL
1234567U

//overflow test
0xffffffff
0xffffffffu
0xfffffffffu
0xfffffffffll
0xffffffffffffffffll
0xffffffffffffffffull
0xfffffffffffffffffull

//floating point numbers
3e2
4e+4
738e-2f
738e-2F
738e-2l
738e-2Lf //pay special attention to this case
463724e-2
463724e-2f
.3243e2
.3243e2f
7932.213e-3l

//characters
't' 'N'
'\n'
'\r' '\a' '\v' '\f'
'\'' '\"' '\\' 
'\?'
'\034'
'\346'
'\x4f'
L'\n'

//string
"abcdefghdfadfefjdkas;lfjds"
"a\nbcd\tefg\rhdfadfefjdkas;lfjds"
L"abcdefghdfadfefjdkas;lfjds"

//multi-character tokens
"..."
">>="
"<<="
"+="
"-="
"*="
"/="
"%="
"&="
"|="
"^="
"|="
">>"
"<<"
"++"
"--"
"->"
"&&"
"||"
"<="
">="
"=="
"!="
#endif

#if 0
/*
**AD-HOC token.h for testing this lexer.
*/

#ifndef TK
#error "You must define the macro TK before including token.h"
#endif

/*TK(token,      name)*/
TK(AUTO,         "auto")
TK(BREAK,        "break")
TK(CASE,         "case")
TK(CHAR,         "char")
TK(CONST,        "const")
TK(CONTINUE,     "continue")
TK(DEFAULT,      "default")
TK(DO,           "do")
TK(DOUBLE,       "double")
TK(ELSE,         "else")
TK(ENUM,         "enum")
TK(EXTERN,       "extern")
TK(FLOAT,        "float")
TK(FOR,          "for")
TK(GOTO,         "goto")
TK(IF,           "if")
TK(INT,          "int")
TK(LONG,         "long")
TK(REGISTER,     "register")
TK(RETURN,       "return")
TK(SHORT,        "short")
TK(SIGNED,       "signed")
TK(SIZEOF,       "sizeof")
TK(STATIC,       "static")
TK(STRUCT,       "struct")
TK(SWITCH,       "switch")
TK(TYPEDEF,      "typedef")
TK(UNION,        "union")
TK(UNSIGNED,     "unsigned")
TK(VOID,         "void")
TK(VOLATILE,     "volatile")
TK(WHILE,        "while")
TK(IDENTIFIER,   "IDENTIFIER")
TK(INTCONST,     "integer")
TK(UINT,         "unsigned integer")
TK(LINT,         "long integer")
TK(ULINT,        "unsigned long integer")
TK(LLINT,        "long long integer")
TK(ULLINT,       "unsigned long long integer")
TK(DOUBLECONST,  "double const")
TK(LDOUBLECONST, "long double")
TK(FLOATCONST,   "float const")
TK(STRING,       "const string")
TK(ELLIPSIS,     "...")
TK(RIGHT_ASSIGN, ">>=")
TK(LEFT_ASSIGN,  "<<=")
TK(ADD_ASSIGN,   "+=")
TK(SUB_ASSIGN,   "-=")
TK(MUL_ASSIGN,   "*=")
TK(DIV_ASSIGN,   "/=")
TK(MOD_ASSIGN,   "%=")
TK(AND_ASSIGN,   "&=")
TK(XOR_ASSIGN,   "^=")
TK(OR_ASSIGN,    "|=")
TK(RIGHT_SHIFT,  ">>")
TK(LEFT_SHIFT,   "<<")
TK(INC_OP,       "++")
TK(DEC_OP,       "--")
TK(PTR_OP,       "->")
TK(AND_OP,       "&&")
TK(OR_OP,        "||")
TK(LE_OP,        "<=")
TK(GE_OP,        ">=")
TK(EQ_OP,        "==")
TK(NE_OP,        "!=")
/*TK(SEMI,         ";")*/
/*TK(LCURLY,       "{")*/
/*TK(RCURLY,       "}")*/
/*TK(COMMA,        ",")*/
/*TK(COLON,        ":")*/
/*TK(ASSIGN,       "=")*/
/*TK(LP,           "(")*/
/*TK(RP,           ")")*/
/*TK(LB,           "[")*/
/*TK(RB,           "]")*/
/*TK(DOT,          ".")*/
/*TK(AND,          "&")*/
/*TK(NOT,          "!")*/
/*TK(COMP,         "~")*/
/*TK(SUB,          "-")*/
/*TK(ADD,          "+")*/
/*TK(MUL,          "*")*/
/*TK(DIV,          "/")*/
/*TK(MOD,          "%")*/
/*TK(LESS,         "<")*/
/*TK(GREATER,      ">")*/
/*TK(XOR,          "^")*/
/*TK(OR,           "|")*/
/*TK(QUESTION,     "?")*/

#endif

static void input_init(char *f)
{
  file = f;
}

int main(int argc, char *argv[]) 
{
  char * infile;
  int tok;

  if(argc != 2){
    fprintf(stderr,"usage: hcc input-file-name.hcc\n");
    return 1;
  }

  input_init(argv[1]);
  infile = argv[1];
  if(!infile || freopen(infile, "r", stdin)==NULL) {
    fprintf(stderr,"%s: can not read file: '%s'\n", argv[0], infile);
    exit(1);
  } 

  while(1) {
    tok = yylex();
    
    if(tok == 0) break;

    if(tok < 256) {
      info(&tcoord,"%c",tok);
      continue;
    }

    switch(tok) {
      case AUTO: case BREAK: case CASE: case CHAR:
      case CONST: case CONTINUE: case DEFAULT: case DO:
      case DOUBLE: case ELSE: case ENUM: case EXTERN:
      case FLOAT: case FOR: case GOTO: case IF: case INT:
      case LONG: case REGISTER: case RETURN: case SHORT:
      case SIGNED: case SIZEOF: case STATIC: case STRUCT:
      case SWITCH: case TYPEDEF: case UNION: case UNSIGNED:
      case VOID: case VOLATILE: case WHILE: 
        info(&tcoord,"string token: %s",tokenstrs[tok-DUMMYTOKEN-1]);
        break;
      case IDENTIFIER:
        info(&tcoord,"identifier: %s",(char*)tval.p);
        break;
      case INTCONST:
        info(&tcoord,"const: %s val: %d",tokenstrs[tok-DUMMYTOKEN-1], tval.i[0]);
        break;
      case UINT:
        info(&tcoord,"const: %s val: %u",tokenstrs[tok-DUMMYTOKEN-1], tval.i[0]);
        break;
      case LINT:
        info(&tcoord,"const: %s val: %ld",tokenstrs[tok-DUMMYTOKEN-1],tval.i[0]);
        break;
      case ULINT:
        info(&tcoord,"const: %s val: %lu",tokenstrs[tok-DUMMYTOKEN-1],tval.i[0]);
        break;
      case LLINT:
        info(&tcoord,"const: %s val: %lld",tokenstrs[tok-DUMMYTOKEN-1],*((long long *)tval.i));
        break;
      case ULLINT:
        info(&tcoord,"const: %s val: %llu",tokenstrs[tok-DUMMYTOKEN-1],*((unsigned long long*)tval.i));
        break;
      case FLOATCONST:
        info(&tcoord,"const: %s val: %f",tokenstrs[tok-DUMMYTOKEN-1],tval.f);
        break;
      case DOUBLECONST:
        info(&tcoord,"const: %s val: %f",tokenstrs[tok-DUMMYTOKEN-1],tval.d);
        break;
      case LDOUBLECONST:
        info(&tcoord,"const: %s val: %f",tokenstrs[tok-DUMMYTOKEN-1],tval.d);
        break;
      case STRING:
        info(&tcoord,"const string: %s",(char*)tval.p);
        break;
      case ELLIPSIS:
        info(&tcoord,"multi-character token: ELLIPSIS");
        break;
      case RIGHT_ASSIGN:
        info(&tcoord,"multi-character token: RIGHT_ASSIGN");
        break;
      case LEFT_ASSIGN:
        info(&tcoord,"multi-character token: LEFT_ASSIGN");
        break;
      case ADD_ASSIGN:
        info(&tcoord,"multi-character token: ADD_ASSIGN");
        break;
      case SUB_ASSIGN:
        info(&tcoord,"multi-character token: SUB_ASSIGN");
        break;
      case MUL_ASSIGN:
        info(&tcoord,"multi-character token: MUL_ASSIGN");
        break;
      case DIV_ASSIGN:
        info(&tcoord,"multi-character token: DIV_ASSIGN");
        break;
      case MOD_ASSIGN:
        info(&tcoord,"multi-character token: MOD_ASSIGN");
        break;
      case AND_ASSIGN:
        info(&tcoord,"multi-character token: AND_ASSIGN");
        break;
      case XOR_ASSIGN:
        info(&tcoord,"multi-character token: XOR_ASSIGN");
        break;
      case OR_ASSIGN:
        info(&tcoord,"multi-character token: OR_ASSIGN");
        break;
      case RIGHT_SHIFT:
        info(&tcoord,"multi-character token: RIGHT_SHIFT");
        break;
      case LEFT_SHIFT:
        info(&tcoord,"multi-character token: LEFT_SHIFT");
        break;
      case INC_OP:
        info(&tcoord,"multi-character token: INC_OP");
        break;
      case DEC_OP:
        info(&tcoord,"multi-character token: DEC_OP");
        break;
      case PTR_OP:
        info(&tcoord,"multi-character token: PTR_OP");
        break;
      case AND_OP:
        info(&tcoord,"multi-character token: AND_OP");
        break;
      case OR_OP:
        info(&tcoord,"multi-character token: OR_OP");
        break;
      case LE_OP:
        info(&tcoord,"multi-character token: LE_OP");
        break;
      case GE_OP:
        info(&tcoord,"multi-character token: GE_OP");
        break;
      case EQ_OP:
        info(&tcoord,"multi-character token: EQ_OP");
        break;
      case NE_OP:
        info(&tcoord,"multi-character token: NE_OP");
        break;

      default: assert(0);
    }
  }

  deallocate();
  return 0;
}
#endif

